name: Java CI

on:
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cache Maven
      id: cache-maven
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven
    
    - name: Checkout Streamsets
      uses: actions/checkout@v2.0.0
      with:
        repository: streamsets/datacollector
        ref: 3.8.2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Build streamsets httpcommonlib
      run: mvn -pl httpcommonlib -am clean install -DskipTests
    
    - uses: actions/checkout@v2.0.0
    
    - name: Build with Maven
      run: mvn install package -DskipTests
    
    - uses: actions/upload-artifact@v1
      with:
        name: anodot-${GITHUB_REF/refs\/tags\//}
        path: target/anodot-${GITHUB_REF/refs\/tags\//}-SNAPSHOT.tar.gz
